# Generated by Django 5.2.7 on 2025-10-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Anônimo', max_length=20)),
                ('mensagem', models.CharField()),
            ],
        ),
    ]
